all:
	(cd panel_b18; make)
	(cd panel_pidp1; make)
	(cd panel_pidp10; make)
	(cd tools; make)
	(cd whirlwind; make)
	(cd tx0; make)
	(cd pdp1; make)
	(cd vpanel_b18; make)
	(cd vpanel_pdp1; make)
	(cd vpanel_whirlwind; make)
