
Element lights[] = {
#define G &grid1
	{ lamptex, G, 2,  4, 0, 0 },
	{ lamptex, G, 3,  4, 0, 0 },
	{ lamptex, G, 4,  4, 0, 0 },
	{ lamptex, G, 5,  4, 0, 0 },
	{ lamptex, G, 6,  4, 0, 0 },
	{ lamptex, G, 7,  4, 0, 0 },
	{ lamptex, G, 8,  4, 0, 0 },
	{ lamptex, G, 9,  4, 0, 0 },
	{ lamptex, G, 10, 4, 0, 0 },
	{ lamptex, G, 11, 4, 0, 0 },
	{ lamptex, G, 12, 4, 0, 0 },
	{ lamptex, G, 13, 4, 0, 0 },
	{ lamptex, G, 14, 4, 0, 0 },
	{ lamptex, G, 15, 4, 0, 0 },
	{ lamptex, G, 16, 4, 0, 0 },
	{ lamptex, G, 17, 4, 0, 0 },
	{ lamptex, G, 18, 4, 0, 0 },
	{ lamptex, G, 19, 4, 0, 0 },

	{ lamptex, G, 2,  6, 0, 0 },
	{ lamptex, G, 3,  6, 0, 0 },
	{ lamptex, G, 4,  6, 0, 0 },
	{ lamptex, G, 5,  6, 0, 0 },
	{ lamptex, G, 6,  6, 0, 0 },
	{ lamptex, G, 7,  6, 0, 0 },
	{ lamptex, G, 8,  6, 0, 0 },
	{ lamptex, G, 9,  6, 0, 0 },
	{ lamptex, G, 10, 6, 0, 0 },
	{ lamptex, G, 11, 6, 0, 0 },
	{ lamptex, G, 12, 6, 0, 0 },
	{ lamptex, G, 13, 6, 0, 0 },
	{ lamptex, G, 14, 6, 0, 0 },
	{ lamptex, G, 15, 6, 0, 0 },
	{ lamptex, G, 16, 6, 0, 0 },
	{ lamptex, G, 17, 6, 0, 0 },
	{ lamptex, G, 18, 6, 0, 0 },
	{ lamptex, G, 19, 6, 0, 0 },

	{ lamptex, G, 21, 6, 0, 0 },
	{ lamptex, G, 22, 6, 0, 0 },
	{ lamptex, G, 23, 6, 0, 0 },
	{ lamptex, G, 24, 6, 0, 0 },

	{ lamptex, G, 21, 4, 0, 0 },
	{ lamptex, G, 22, 4, 0, 0 },
	{ lamptex, G, 23, 4, 0, 0 },
	{ lamptex, G, 24, 4, 0, 0 },

	{ lamptex, G, 21, 2, 0, 0 },
	{ lamptex, G, 22, 2, 0, 0 },
	{ lamptex, G, 23, 2, 0, 0 },
	{ lamptex, G, 24, 2, 0, 0 },

	{ lamptex, G, 27, 1, 0, 0 },
	{ lamptex, G, 27, 2, 0, 0 },
	{ lamptex, G, 27, 3, 0, 0 },
	{ lamptex, G, 27, 4, 0, 0 },
	{ lamptex, G, 27, 5, 0, 0 },
	{ lamptex, G, 27, 6, 0, 0 },
#undef G
};

Element switches[] = {
#define G &grid1
	{ switchtex, G, 2,  8, 0, 0 },
	{ switchtex, G, 3,  8, 0, 0 },
	{ switchtex, G, 4,  8, 0, 0 },
	{ switchtex, G, 5,  8, 0, 0 },
	{ switchtex, G, 6,  8, 0, 0 },
	{ switchtex, G, 7,  8, 0, 0 },
	{ switchtex, G, 8,  8, 0, 0 },
	{ switchtex, G, 9,  8, 0, 0 },
	{ switchtex, G, 10, 8, 0, 0 },
	{ switchtex, G, 11, 8, 0, 0 },
	{ switchtex, G, 12, 8, 0, 0 },
	{ switchtex, G, 13, 8, 0, 0 },
	{ switchtex, G, 14, 8, 0, 0 },
	{ switchtex, G, 15, 8, 0, 0 },
	{ switchtex, G, 16, 8, 0, 0 },
	{ switchtex, G, 17, 8, 0, 0 },
	{ switchtex, G, 18, 8, 0, 0 },
	{ switchtex, G, 19, 8, 0, 0 },

	{ hswitchtex, G, 28.5, 1, 0, 0 },
	{ hswitchtex, G, 28.5, 2, 0, 0 },
	{ hswitchtex, G, 28.5, 3, 0, 0 },
	{ hswitchtex, G, 28.5, 4, 0, 0 },
	{ hswitchtex, G, 28.5, 5, 0, 0 },
	{ hswitchtex, G, 28.5, 6, 0, 0 },
#undef G
};

Element btns[] = {
#define G &grid1
	{ btntex, G, 21, 8, 0, 0 },
	{ btntex, G, 22, 8, 0, 0 },
	{ btntex, G, 23, 8, 0, 0 },
	{ btntex, G, 24, 8, 0, 0 },
	{ btntex, G, 25, 8, 0, 0 },
	{ btntex, G, 26, 8, 0, 0 },
	{ btntex, G, 27, 8, 0, 0 },
	{ btntex, G, 28, 8, 0, 0 },

	{ btntex, G, 25, 4, 0, 0 },
	{ btntex, G, 26, 4, 0, 0 },

	{ btntex, G, 25, 6, 0, 0 },
	{ btntex, G, 26, 6, 0, 0 },
#undef G
};
