
Element lights[] = {
#define G &grid1
	// PC
	{ lamptex, G, 5, 3, 0, 0 },
	{ lamptex, G, 6, 3, 0, 0 },
	{ lamptex, G, 7, 3, 0, 0 },
	{ lamptex, G, 8, 3, 0, 0 },
	{ lamptex, G, 9, 3, 0, 0 },
	{ lamptex, G, 10, 3, 0, 0 },
	{ lamptex, G, 11, 3, 0, 0 },
	{ lamptex, G, 12, 3, 0, 0 },
	{ lamptex, G, 13, 3, 0, 0 },
	{ lamptex, G, 14, 3, 0, 0 },
	{ lamptex, G, 15, 3, 0, 0 },
	{ lamptex, G, 16, 3, 0, 0 },
	{ lamptex, G, 17, 3, 0, 0 },
	{ lamptex, G, 18, 3, 0, 0 },
	{ lamptex, G, 19, 3, 0, 0 },
	{ lamptex, G, 20, 3, 0, 0 },

	// MA
	{ lamptex, G, 5,  5, 0, 0 },
	{ lamptex, G, 6,  5, 0, 0 },
	{ lamptex, G, 7,  5, 0, 0 },
	{ lamptex, G, 8,  5, 0, 0 },
	{ lamptex, G, 9,  5, 0, 0 },
	{ lamptex, G, 10, 5, 0, 0 },
	{ lamptex, G, 11, 5, 0, 0 },
	{ lamptex, G, 12, 5, 0, 0 },
	{ lamptex, G, 13, 5, 0, 0 },
	{ lamptex, G, 14, 5, 0, 0 },
	{ lamptex, G, 15, 5, 0, 0 },
	{ lamptex, G, 16, 5, 0, 0 },
	{ lamptex, G, 17, 5, 0, 0 },
	{ lamptex, G, 18, 5, 0, 0 },
	{ lamptex, G, 19, 5, 0, 0 },
	{ lamptex, G, 20, 5, 0, 0 },

	// MB
	{ lamptex, G, 3,  7, 0, 0 },
	{ lamptex, G, 4,  7, 0, 0 },
	{ lamptex, G, 5,  7, 0, 0 },
	{ lamptex, G, 6,  7, 0, 0 },
	{ lamptex, G, 7,  7, 0, 0 },
	{ lamptex, G, 8,  7, 0, 0 },
	{ lamptex, G, 9,  7, 0, 0 },
	{ lamptex, G, 10, 7, 0, 0 },
	{ lamptex, G, 11, 7, 0, 0 },
	{ lamptex, G, 12, 7, 0, 0 },
	{ lamptex, G, 13, 7, 0, 0 },
	{ lamptex, G, 14, 7, 0, 0 },
	{ lamptex, G, 15, 7, 0, 0 },
	{ lamptex, G, 16, 7, 0, 0 },
	{ lamptex, G, 17, 7, 0, 0 },
	{ lamptex, G, 18, 7, 0, 0 },
	{ lamptex, G, 19, 7, 0, 0 },
	{ lamptex, G, 20, 7, 0, 0 },

	// AC
	{ lamptex, G, 3,  9, 0, 0 },
	{ lamptex, G, 4,  9, 0, 0 },
	{ lamptex, G, 5,  9, 0, 0 },
	{ lamptex, G, 6,  9, 0, 0 },
	{ lamptex, G, 7,  9, 0, 0 },
	{ lamptex, G, 8,  9, 0, 0 },
	{ lamptex, G, 9,  9, 0, 0 },
	{ lamptex, G, 10, 9, 0, 0 },
	{ lamptex, G, 11, 9, 0, 0 },
	{ lamptex, G, 12, 9, 0, 0 },
	{ lamptex, G, 13, 9, 0, 0 },
	{ lamptex, G, 14, 9, 0, 0 },
	{ lamptex, G, 15, 9, 0, 0 },
	{ lamptex, G, 16, 9, 0, 0 },
	{ lamptex, G, 17, 9, 0, 0 },
	{ lamptex, G, 18, 9, 0, 0 },
	{ lamptex, G, 19, 9, 0, 0 },
	{ lamptex, G, 20, 9, 0, 0 },

	// IO
	{ lamptex, G, 3,  11, 0, 0 },
	{ lamptex, G, 4,  11, 0, 0 },
	{ lamptex, G, 5,  11, 0, 0 },
	{ lamptex, G, 6,  11, 0, 0 },
	{ lamptex, G, 7,  11, 0, 0 },
	{ lamptex, G, 8,  11, 0, 0 },
	{ lamptex, G, 9,  11, 0, 0 },
	{ lamptex, G, 10, 11, 0, 0 },
	{ lamptex, G, 11, 11, 0, 0 },
	{ lamptex, G, 12, 11, 0, 0 },
	{ lamptex, G, 13, 11, 0, 0 },
	{ lamptex, G, 14, 11, 0, 0 },
	{ lamptex, G, 15, 11, 0, 0 },
	{ lamptex, G, 16, 11, 0, 0 },
	{ lamptex, G, 17, 11, 0, 0 },
	{ lamptex, G, 18, 11, 0, 0 },
	{ lamptex, G, 19, 11, 0, 0 },
	{ lamptex, G, 20, 11, 0, 0 },

	// flip-flops
	{ lamptex, G, 23, 3, 0, 0 },
	{ lamptex, G, 23, 4, 0, 0 },
	{ lamptex, G, 23, 5, 0, 0 },
	{ lamptex, G, 23, 6, 0, 0 },
	{ lamptex, G, 23, 7, 0, 0 },
	{ lamptex, G, 23, 8, 0, 0 },
	{ lamptex, G, 23, 9, 0, 0 },
	{ lamptex, G, 23, 10, 0, 0 },
	{ lamptex, G, 23, 11, 0, 0 },
	{ lamptex, G, 23, 12, 0, 0 },
	{ lamptex, G, 23, 13, 0, 0 },
	{ lamptex, G, 23, 14, 0, 0 },
	{ lamptex, G, 23, 15, 0, 0 },
#undef G

#define G &grid2
	// run, single step, single inst
	{ lamptex, G, 29, 3, 0, 0 },
	{ lamptex, G, 29, 4, 0, 0 },
	{ lamptex, G, 29, 5, 0, 0 },

	// sense switches
	{ lamptex, G, 29, 7.5, 0, 0 },
	{ lamptex, G, 30, 7.5, 0, 0 },
	{ lamptex, G, 31, 7.5, 0, 0 },
	{ lamptex, G, 32, 7.5, 0, 0 },
	{ lamptex, G, 33, 7.5, 0, 0 },
	{ lamptex, G, 34, 7.5, 0, 0 },

	// program flags
	{ lamptex, G, 29, 11.7, 0, 0 },
	{ lamptex, G, 30, 11.7, 0, 0 },
	{ lamptex, G, 31, 11.7, 0, 0 },
	{ lamptex, G, 32, 11.7, 0, 0 },
	{ lamptex, G, 33, 11.7, 0, 0 },
	{ lamptex, G, 34, 11.7, 0, 0 },

	// IR
	{ lamptex, G, 29, 14.5, 0, 0 },
	{ lamptex, G, 30, 14.5, 0, 0 },
	{ lamptex, G, 31, 14.5, 0, 0 },
	{ lamptex, G, 32, 14.5, 0, 0 },
	{ lamptex, G, 33, 14.5, 0, 0 },
#undef G
};

Element switches[] = {
#define G &grid1
	// extend
	{ switchtex, G, 3,  13, 0, 0 },
	// TA
	{ switchtex, G, 5,  13, 0, 0 },
	{ switchtex, G, 6,  13, 0, 0 },
	{ switchtex, G, 7,  13, 0, 0 },
	{ switchtex, G, 8,  13, 0, 0 },
	{ switchtex, G, 9,  13, 0, 0 },
	{ switchtex, G, 10, 13, 0, 0 },
	{ switchtex, G, 11, 13, 0, 0 },
	{ switchtex, G, 12, 13, 0, 0 },
	{ switchtex, G, 13, 13, 0, 0 },
	{ switchtex, G, 14, 13, 0, 0 },
	{ switchtex, G, 15, 13, 0, 0 },
	{ switchtex, G, 16, 13, 0, 0 },
	{ switchtex, G, 17, 13, 0, 0 },
	{ switchtex, G, 18, 13, 0, 0 },
	{ switchtex, G, 19, 13, 0, 0 },
	{ switchtex, G, 20, 13, 0, 0 },

	// TW
	{ switchtex, G, 3,  15, 0, 0 },
	{ switchtex, G, 4,  15, 0, 0 },
	{ switchtex, G, 5,  15, 0, 0 },
	{ switchtex, G, 6,  15, 0, 0 },
	{ switchtex, G, 7,  15, 0, 0 },
	{ switchtex, G, 8,  15, 0, 0 },
	{ switchtex, G, 9,  15, 0, 0 },
	{ switchtex, G, 10, 15, 0, 0 },
	{ switchtex, G, 11, 15, 0, 0 },
	{ switchtex, G, 12, 15, 0, 0 },
	{ switchtex, G, 13, 15, 0, 0 },
	{ switchtex, G, 14, 15, 0, 0 },
	{ switchtex, G, 15, 15, 0, 0 },
	{ switchtex, G, 16, 15, 0, 0 },
	{ switchtex, G, 17, 15, 0, 0 },
	{ switchtex, G, 18, 15, 0, 0 },
	{ switchtex, G, 19, 15, 0, 0 },
	{ switchtex, G, 20, 15, 0, 0 },
#undef G

#define G &grid2
	// run, single step, single inst
	{ hswitchtex, G, 30.5, 3, 0, 0 },
	{ hswitchtex, G, 30.5, 4, 0, 0 },
	{ hswitchtex, G, 30.5, 5, 0, 0 },

	// sense switches
	{ switchtex, G, 29, 9, 0, 0 },
	{ switchtex, G, 30, 9, 0, 0 },
	{ switchtex, G, 31, 9, 0, 0 },
	{ switchtex, G, 32, 9, 0, 0 },
	{ switchtex, G, 33, 9, 0, 0 },
	{ switchtex, G, 34, 9, 0, 0 },
#undef G
};

Element keys[] = {
#define G &grid1
	{ keytex, G, 4,  19, 0, 0 },
	{ keytex, G, 7,  19, 0, 0 },
	{ keytex, G, 10, 19, 0, 0 },
	{ keytex, G, 13, 19, 0, 0 },
	{ keytex, G, 16, 19, 0, 0 },
	{ keytex, G, 19, 19, 0, 0 },
	{ keytex, G, 28, 19, 0, 0 },
	{ keytex, G, 31, 19, 0, 0 },
#undef G
};
